---
- name: Set customize_user
  when: customize_user is not defined
  block:
    - name: Get currently installed username
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1 | head -n 1
      args:
        executable: /bin/bash
      register: _customize_user
      changed_when: false

    - name: Set user to be used for customization
      ansible.builtin.set_fact:
        customize_user: '{{ _customize_user.stdout }}'

- name: Install util applications
  become: true
  ansible.builtin.apt:
    name:
      - dconf-editor
      - dbus
      - dbus-x11
    update_cache: true
    cache_valid_time: 3600

- name: Set dconf profile
  become: true
  become_user: '{{ customize_user }}'
  ansible.builtin.copy:
    dest: /home/{{ customize_user }}/profile
    content: user-db:user

- name: Set default background
  become: true
  become_user: '{{ customize_user }}'
  ansible.builtin.shell: |
    dbus-launch dconf load / << EOF 
    [org/mate/desktop/background]
    picture-filename=''
    EOF
  environment:
    DISPLAY: ':0'
  changed_when: true
